/* Vite configuration for the Word Quest standalone app.
   The app imports the game logic from ../src/engine.js. The extractor generates
   that module from the reference build before each dev run and each build. */
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ICONS_DIR = path.resolve(__dirname, "../icons");
const DIST_DIR = path.resolve(__dirname, "dist");

/* Walk a directory and return every file path relative to that directory. */
function walk(dir, prefix = "") {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? prefix + "/" + entry.name : entry.name;
    if (entry.isDirectory()) out.push(...walk(path.join(dir, entry.name), rel));
    else out.push(rel);
  }
  return out;
}

/* Copies the shared icon set into the bundle and writes a cache-first service
   worker whose precache list is the exact build output. The app then operates
   offline after the first load and makes no further network calls. */
function wqPwa() {
  return {
    name: "wq-pwa",
    buildStart() {
      for (const f of readdirSync(ICONS_DIR)) {
        this.emitFile({
          type: "asset",
          fileName: "icons/" + f,
          source: readFileSync(path.join(ICONS_DIR, f)),
        });
      }
    },
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const m = req.url && req.url.match(/^\/icons\/([^?]+)$/);
        if (!m) return next();
        const file = path.resolve(ICONS_DIR, decodeURIComponent(m[1]));
        if (!file.startsWith(ICONS_DIR + path.sep)) return next();
        try {
          const data = readFileSync(file);
          res.setHeader("Content-Type", file.endsWith(".ico") ? "image/x-icon" : "image/png");
          res.end(data);
        } catch {
          next();
        }
      });
    },
    closeBundle() {
      const files = walk(DIST_DIR).filter((f) => f !== "sw.js");
      const assets = files.map((f) => "./" + f).sort();
      const version = createHash("sha256").update(assets.join("\n")).digest("hex").slice(0, 12);
      const sw = `/* GENERATED by vite.config.js (wq-pwa) — do not edit by hand.
   Cache-first service worker. After the first load the app is fully cached
   and makes no network calls. */
const CACHE = "wq-${version}";
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === "navigate") {
    e.respondWith(caches.match("./index.html").then((r) => r || fetch(req)));
    return;
  }
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      });
    })
  );
});
`;
      writeFileSync(path.join(DIST_DIR, "sw.js"), sw);
      console.log(`wq-pwa: wrote sw.js (${assets.length} precached assets, cache wq-${version})`);
    },
  };
}

export default defineConfig({
  /* Relative base: the built app works from any path, including a GitHub
     Pages project path. */
  base: "./",
  plugins: [react(), tailwindcss(), wqPwa()],
  resolve: {
    alias: { "@engine": path.resolve(__dirname, "../src/engine.js") },
  },
  server: {
    fs: { allow: [path.resolve(__dirname, "..")] },
  },
  build: {
    /* Minimum platform is iPadOS 15.4 (SPEC section 8). */
    target: ["es2020", "safari15"],
  },
});
