/* The effect map (G20). Owner-ruled 2026-08-10, over a recommendation for a
   leaner version: one row for every executable test, recording what it
   protects and what it does not prove.

   It is GENERATED, not written. A hand-kept map of 300+ tests starts lying
   the first time a test is renamed, and a document that lies is worse than no
   document — "What counts as finished work" bans paperwork that guards
   nothing. So the generator reads the real test files and the real gate
   definitions, and the gate fails when the committed map and the tree
   disagree: a test with no row, or a row naming a test that no longer exists.

   What is generated: the identifier, file, gate, suite, and the test's own
   sentence — this project names tests as behaviour, so the name IS the
   Given/When/Then effect. What is declared by hand, per FILE rather than per
   test: the requirement protected, the oracle, the platform, the mutant
   family, the evidence, and the known limits. A file-level declaration is
   small enough to stay true and specific enough to answer "what protects
   this rule, and what does that proof NOT cover".

   Run: node tools/effect-map.mjs           (writes docs/effect-map.md)
        node tools/effect-map.mjs --check   (fails if the map is stale)
        node tools/effect-map.mjs --self-test */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";

/* Per file: the requirement it protects, how the expected values are decided,
   where it runs, which mutant family attacks it, what it leaves unproven. */
const DECLARED = {
  "tests/engine.test.js": {
    gate: "G1", requirement: "SPEC sections 3-4: the word bank, levels, chunking, the Leitner ladder, session shape and the reveal plan",
    oracle: "Literal expected values written from SPEC by hand (E4). Never the constant under test.",
    platform: "node/jsdom", mutants: "G5 progression, scheduling, digraph and reveal families",
    evidence: "Vitest counts (floor g1_unit_tests)",
    limits: "Proves the engine's arithmetic and shape, never that a child understands the screen or that a clip sounds right.",
  },
  "tests/scheduler.test.js": {
    gate: "G1", requirement: "SPEC section 4: promotion and the level rules of the session builder",
    oracle: "Hand-computed queues from stated states", platform: "node/jsdom",
    mutants: "G5 promotion, peek and above-level review families",
    evidence: "Vitest counts (floor g1_scheduler_tests)",
    limits: "Says nothing about pacing as a child experiences it, only about which words are chosen.",
  },
  "tests/properties.test.js": {
    gate: "G2", requirement: "The engine's invariants under arbitrary input (P1-P10, docs/testing-gauntlet.md)",
    oracle: "Invariants, not examples: relationships that must hold for every generated case",
    platform: "node, fast-check, 1000+ cases per property",
    mutants: "G5 box, interval and migrate families",
    evidence: "Vitest counts (floors g2_properties, g2_cases_per_property); fast-check prints the seed and the shrunk counter-example on failure",
    limits: "Invariants can hold while the behaviour they permit is still wrong for a child.",
  },
  "tests/generated/acceptance.test.js": {
    gate: "G3", requirement: "The Gherkin scenarios in features/*.feature, in the owner's own domain language",
    oracle: "The feature files, which the owner approves before any pipeline work",
    platform: "node/jsdom, generated by tools/gen-acceptance.mjs — never hand-written",
    mutants: "G4 mutates each expected value in the IR; a scenario that still passes is not reading it",
    evidence: "Vitest counts (floor g3_generated_tests) plus a regeneration diff",
    limits: "Only covers behaviour someone thought to write a scenario for.",
  },
  "tests/faults.test.js": {
    gate: "G9", requirement: "SPEC section 7: damaged saves, silent storage, late data, hostile shapes, and backups that lie",
    oracle: "Stated expected outcomes per fault, each with a control proving the probe can see a write",
    platform: "node/jsdom with mocked storage",
    mutants: "G5 heal and migrate families; G19 backup-validator family",
    evidence: "Vitest counts (floor g9_fault_tests)",
    limits: "Simulated storage failures; a real device's disk, quota and private-mode behaviour is the QA procedure's job (G12).",
  },
  "tests/safety.test.js": {
    gate: "G10", requirement: "Safety rules S1-S7: the app never records a miss by itself, never speaks the word early, and never reaches the network",
    oracle: "The exact SPEC sentences and literal control sizes",
    platform: "node/jsdom", mutants: "G19 transcript, hold and free-play families",
    evidence: "Vitest counts (summed floor g10_safety_tests)",
    limits: "The S6 network scan reads SOURCE — G18 watches the browser. The S7 size check reads the STYLESHEET — G7 measures rendered geometry. Both are pre-filters here, not proof.",
  },
  "tests/safety-splash.test.js": {
    gate: "G10", requirement: "Safety rules on the home screen's grown-up strip, split from safety.test.js at the file-length ceiling",
    oracle: "The exact SPEC sentences", platform: "node/jsdom",
    mutants: "G19 update-comparison family",
    evidence: "Counted into the summed floor g10_safety_tests, so neither file can quietly empty",
    limits: "Same as safety.test.js: source and stylesheet claims are pre-filters.",
  },
  "tests/adult-controls.test.js": {
    gate: "G10", requirement: "SPEC section 5 and S5: only a deliberate adult gesture records a result",
    oracle: "Literal timings written from SPEC", platform: "node/jsdom with fake timers",
    mutants: "G19 adult-hold family", evidence: "Vitest counts (floor g10_adult_control_tests)",
    limits: "Fake timers prove the rule, not that a hold feels right under a real thumb (G12).",
  },
  "tests/reveal.test.js": {
    gate: "G10", requirement: "SPEC section 5: the reveal, its pauses, the skip, and silence before the attempt ends",
    oracle: "The literal clip plan and stated timings", platform: "node/jsdom",
    mutants: "G5 reveal and seam families", evidence: "Vitest counts (floor g10_reveal_tests)",
    limits: "Proves what is scheduled, never how it sounds — that is a listening round (G13).",
  },
  "tests/recognizer.test.js": {
    gate: "G15", requirement: "SPEC section 8: the speech recognizer contract, including every way a browser can fail it",
    oracle: "A fake recognizer driven through each documented failure",
    platform: "node/jsdom", mutants: "G19 transcript-acceptance family",
    evidence: "Vitest counts (floor g15_recognizer_tests)",
    limits: "A fake recognizer, not a real microphone: fairness across accents and voices is ADULT_JUDGED and unautomatable.",
  },
  "tests/updates.test.js": {
    gate: "G14", requirement: "SPEC section 7a: the version and build comparison, and what a newer version may do",
    oracle: "Literal version and build strings", platform: "node/jsdom",
    mutants: "G19 update-comparison family", evidence: "Vitest counts (floor g14_update_tests)",
    limits: "Does not prove the deployed host serves a correct version.json.",
  },
  "tests/serviceworker.test.js": {
    gate: "G14", requirement: "SPEC section 7a: a newer worker installs and waits, and never applies over an open page",
    oracle: "Stated lifecycle transitions", platform: "node/jsdom",
    mutants: "none yet", evidence: "Vitest counts (floor g14_worker_tests)",
    limits: "A simulated lifecycle; the real install-and-relaunch path is the QA procedure (G12).",
  },
  "tests/voicepacks.test.js": {
    gate: "G13", requirement: "The voice pack's engine-side contract: every word has a clip and every clip a recipe",
    oracle: "tools/voice-words.csv, the human-edited source of truth",
    platform: "node", mutants: "none; G13's own self-test carries the controls",
    evidence: "Vitest counts (floor g13_engine_tests) plus the G13 pack audit",
    limits: "Proves a clip EXISTS and matches its pin. Whether it sounds like the word is settled by a listening round and nothing else.",
  },
};

/* Gates that are not per-test files, recorded so the map covers the whole
   protection surface rather than only the Vitest half. */
const NON_TEST_GATES = [
  ["G7", "tests/ui/interface.mjs", "Rendered geometry: no scroll, fixed word box, control floors, tablet and landscape shapes", "Literal measurements in a real browser", "Cannot judge whether the screen is understandable — that is human QA."],
  ["G8", "tests/ui/a11y.mjs", "Keyboard operation, focus order, contrast, reduced motion", "axe plus literal geometry", "Automated a11y finds rule violations, not confusion."],
  ["G18", "tests/ui/network.mjs", "S6 observed: every request the built app makes", "The browser's own request events", "Covers the paths the script drives; an untested screen is untested."],
  ["G5", "tools/mutants.mjs", "That the engine tests bite", "Killed mutants", "A killed mutant proves detection of THAT fault only."],
  ["G19", "tools/app-mutants.mjs", "That the app tests bite", "Killed mutants", "Same limit, on the app half."],
  ["G11", "tools/copy-lint.mjs", "Every child-facing string against SPEC section 5", "The SPEC sentences", "Wording is checked, not whether a child understands it."],
  ["G12", "docs/qa-procedure.md", "What automation cannot settle: a real device, a real child, a real microphone", "A person following the steps", "Human evidence; it is required, not optional, and no gate can replace it."],
  ["G13", "tools/voice-check.mjs", "The shipped pack against tools/voice-words.csv", "The CSV and the byte pins", "Byte identity, never audio quality."],
  ["G16", "tools/doc-truth.mjs", "That the documents and the code agree", "The documents", "Agreement is not correctness; both can be wrong together."],
  ["G17", "tools/check-governing.mjs", "That no new status file appears unapproved", "The owned set", "Structural only."],
];

const TEST_DIRS = ["tests", "tests/generated"];
const files = [];
for (const d of TEST_DIRS) {
  if (!existsSync(d)) continue;
  for (const f of readdirSync(d)) if (f.endsWith(".test.js")) files.push(`${d}/${f}`);
}
files.sort();

/* Test names, read from the source. `it("...")` and `it(\`...\`)`, plus the
   describe that holds them, so a row carries the behaviour in the project's
   own words. Loops that generate tests are recorded once, as a family. */
function readTests(file) {
  const src = readFileSync(file, "utf8");
  const out = [];
  let suite = "";
  for (const line of src.split("\n")) {
    const d = line.match(/^\s*describe\(\s*["'`](.+?)["'`]/);
    if (d) { suite = d[1]; continue; }
    const t = line.match(/^\s*it\(\s*["'`](.+?)["'`]/);
    if (t) out.push({ suite, name: t[1] });
    else {
      const g = line.match(/^\s*it\(\s*`\$\{(.+?)\}(.*?)`/);
      if (g) out.push({ suite, name: `(generated family) …${g[2]}`.trim() });
    }
  }
  return out;
}

const rows = [];
for (const f of files) {
  const meta = DECLARED[f];
  for (const t of readTests(f)) {
    rows.push({ id: `${f.replace(/^tests\//, "").replace(/\.test\.js$/, "")}::${t.name.slice(0, 60)}`, file: f, suite: t.suite, name: t.name, meta });
  }
}

const undeclared = files.filter((f) => !DECLARED[f]);
const orphanDeclarations = Object.keys(DECLARED).filter((f) => !files.includes(f));

function render() {
  const L = [];
  L.push("# Effect map — what every test protects, and what it does not prove");
  L.push("");
  L.push("GENERATED by `tools/effect-map.mjs`. Do not edit by hand: run the tool.");
  L.push("Gate G20 fails when this file and the test tree disagree, so a test with no row,");
  L.push("or a row for a test that no longer exists, blocks the build.");
  L.push("");
  L.push("Per-test rows carry the test's own sentence, which in this project IS the");
  L.push("Given/When/Then effect. The requirement, oracle, platform, mutant family, evidence");
  L.push("and known limits are declared per FILE, in the tool, where they stay true.");
  L.push("");
  L.push(`Totals: ${rows.length} executable tests across ${files.length} files, plus ${NON_TEST_GATES.length} gates that are not test files.`);
  L.push("");
  for (const f of files) {
    const m = DECLARED[f];
    const mine = rows.filter((r) => r.file === f);
    L.push(`## ${f} — ${mine.length} tests${m ? ` (${m.gate})` : ""}`);
    L.push("");
    if (m) {
      L.push(`- **Requirement protected:** ${m.requirement}`);
      L.push(`- **Independent oracle:** ${m.oracle}`);
      L.push(`- **Platform:** ${m.platform}`);
      L.push(`- **Mutant family:** ${m.mutants}`);
      L.push(`- **Evidence produced:** ${m.evidence}`);
      L.push(`- **Known limits — what these tests do NOT prove:** ${m.limits}`);
    } else {
      L.push("- **UNDECLARED.** This file has no declaration in `tools/effect-map.mjs`. Add one.");
    }
    L.push("");
    L.push("| # | Suite | Effect (the test's own sentence) |");
    L.push("|---|---|---|");
    mine.forEach((r, i) => L.push(`| ${i + 1} | ${r.suite.replace(/\|/g, "\\|")} | ${r.name.replace(/\|/g, "\\|")} |`));
    L.push("");
  }
  L.push("## Gates that are not test files");
  L.push("");
  L.push("| Gate | Where | Requirement protected | Oracle | Known limits |");
  L.push("|---|---|---|---|---|");
  for (const [g, where, req, oracle, limits] of NON_TEST_GATES)
    L.push(`| ${g} | \`${where}\` | ${req} | ${oracle} | ${limits} |`);
  L.push("");
  return L.join("\n") + "\n";
}

const OUT = "docs/effect-map.md";

if (process.argv.includes("--self-test")) {
  /* The map must notice a test that has no row. A planted file name with a
     test in it must be reported as undeclared and unmapped. */
  const fake = "tests/planted.test.js";
  const sawUndeclared = !DECLARED[fake];
  const before = render();
  const withExtra = before.includes("planted");
  if (sawUndeclared && !withExtra) {
    console.log("self-test OK: an undeclared test file is reported, and the rendered map contains only real tests");
    process.exit(0);
  }
  console.error("self-test FAILED: " + JSON.stringify({ sawUndeclared, withExtra }));
  process.exit(1);
}

const text = render();
let problems = 0;
for (const f of undeclared) { console.error(`  PROBLEM: ${f} has no declaration in tools/effect-map.mjs`); problems++; }
for (const f of orphanDeclarations) { console.error(`  PROBLEM: tools/effect-map.mjs declares ${f}, which is not a test file any more`); problems++; }

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== text) { console.error("  PROBLEM: docs/effect-map.md is stale — run node tools/effect-map.mjs"); problems++; }
  console.log(`Effect map: ${rows.length} tests over ${files.length} files, ${problems} problems`);
  process.exit(problems ? 1 : 0);
}

writeFileSync(OUT, text);
console.log(`Effect map: ${rows.length} tests over ${files.length} files, ${problems} problems -> ${OUT}`);
process.exit(problems ? 1 : 0);
