/* THE EXTRACTOR: one reference file, the engine modules and their index
 * (batch 2 of the refactor, owner-ruled 2026-09-12, decision 1: "section
 * markers inside the one reference file, and the extractor emits modules
 * from them; no rule changes; the hand-typed export list goes away").
 *
 * WHAT IT MAKES. reference/word-quest.jsx stays one file that runs as a chat
 * artifact (E2). Everything before the component banner is the engine, and
 * inside it a `/* @engine <name> *\/` marker comment opens each section, in
 * the order SECTIONS below fixes. Each section becomes src/engine/<name>.js:
 * one `import` line for every section above it whose names it uses, the
 * section's text verbatim, and one `export { ... }` clause naming every
 * top-level declaration it makes; src/engine.js is the index that re-exports
 * every section, so nothing that imports the engine changes. Writing the
 * engine also deletes any module a renamed or removed section left behind in
 * that folder, so a stale module can never be linted, counted or imported -
 * and it refuses to delete or write at all where a .js file it did not write
 * (no GENERATED header) sits in that folder or at the index's own path. The export
 * surface is DERIVED from the declarations: the list of 100 names this file
 * used to type by hand - 8 of them imported by nobody - is gone. The clause
 * sits at the end rather than an `export` keyword on each declaration so the
 * body stays byte-for-byte the reference's: an `export` token in front of
 * `const TRICKY` made the shape gate's duplication window at that seam match
 * the tools' exported string lists, one region more than the ceiling allows,
 * and E6 does not let a ceiling rise for a keyword.
 *
 * WHAT IT REFUSES, each with a control in --self-test:
 *   - a marker missing, doubled, unknown or out of order; code before the
 *     first marker; a marker line inside a statement; an engine that does
 *     not parse;
 *   - a forward reference: a section using a name a LATER section declares.
 *     The order of the sections is the order of the imports, so a cycle is
 *     impossible by construction - a forward reference is a cycle in waiting;
 *   - a name DECLARED in two sections (a `var` twice): one binding in the
 *     one file, two declarations the modules cannot load;
 *   - a section ASSIGNING to a name another section declares: the one-file
 *     reference runs it, and the modules throw, because an imported binding
 *     cannot be assigned (found by the refactor's engineer, 2026-09-13, with
 *     a plant the first version accepted);
 *   - a name app/src, tests or tools import from the engine that no section
 *     declares (the scan reads static imports and destructured dynamic
 *     imports of "@engine" and of any ".../src/engine.js");
 *   - an output that differs between two extractions of the same input (the
 *     gauntlet's 77-times rule: every extraction is byte-identical).
 *
 * HOW IT READS THE CODE. ESLint's own parser and scope manager, in process,
 * the way tools/shape.mjs reads complexity: the module scope's bindings are
 * the declarations and their references are the uses, so a property key or
 * a word in a string never counts as a use and a shorthand property does.
 * No line of logic changes, and the self-test proves the engine's body
 * comes back from the modules line for line.
 *
 * Run:      node tools/extract-engine.mjs [reference] [index]
 *           (defaults reference/word-quest.jsx and src/engine.js, both from
 *           the repository root; arguments given are from the working
 *           directory, which is how app/package.json runs it from app/; the
 *           modules land beside the index in a folder of the index's own name;
 *           the import scan always reads app/src, tests and tools from the
 *           repository root, and the line it prints says how many it checked)
 * Needs:    the ROOT install (npm ci at the repository root): the reader is
 *           ESLint's parser, which the app's own install does not carry.
 * Controls: node tools/extract-engine.mjs --self-test
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync, rmSync } from "node:fs";
import { dirname, resolve, join, basename, extname, relative, sep } from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";
import { finish } from "./lib/selftest.mjs";
import { run, withScratch } from "./lib/proc.mjs";

export const SECTIONS = ["content", "palette", "chunker", "session", "speech", "sounds", "bends", "ladder", "voice", "roster", "storage", "trays", "export"];
const MARKER = /^\/\* @engine ([a-z]+) \*\/$/;
const BANNER = "/* ============================================================ */\n\nexport default function WordQuest()";
const HEADER = "/* GENERATED by tools/extract-engine.mjs — do not edit by hand. */\n";
const REFERENCE = "reference/word-quest.jsx";
const INDEX = "src/engine.js";
/* THE REPOSITORY ROOT, from this file's own place and never from the working
   directory. app/package.json runs the extractor from app/ (predev and
   prebuild), and with roots read from the working directory the import scan
   found no folder there and silently checked nothing while the line it
   printed said the engine was written: 0 names from app/, 342 from the root
   (the refactor's engineer, 2026-09-13). A root the scan cannot find is now
   refused, not skipped. */
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const IMPORT_ROOTS = ["app/src", "tests", "tools"].map((r) => join(ROOT, r));

/* A refusal is the extractor's own verdict on its input; anything else that
   throws is a fault in the extractor, and the controls tell the two apart. */
class Refusal extends Error {}
const refuse = (why) => { throw new Refusal(why); };
const posix = (p) => relative(ROOT, resolve(p)).split(sep).join("/");

/* ESLint, loaded when this module loads, with a failure KEPT rather than
   thrown: doc-truth, the gauntlet and quality-control import SECTIONS from
   here and must load without it, and the command must say what to do instead
   of printing a stack trace. The README's app path (install the app, run it)
   met exactly that stack trace once the reader became ESLint's parser -
   reproduced 2026-09-13 in a clean clone with no install: the app's prebuild
   died on "Cannot find package 'eslint'", where the same command before
   batch 2 wrote the engine. */
const LINT_HELP = "run npm ci at the repository root first: the extractor reads the reference with ESLint's parser, and the app's own install does not carry it";
async function loadLinter(importer = (spec) => import(spec)) {
  try { return { Linter: (await importer("eslint")).Linter, missing: null }; }
  catch (e) {
    /* Only a missing package gets the install advice. A broken install is its
       own fault, and advice to run npm ci would hide it: thrown as it is. */
    if (!e || e.code !== "ERR_MODULE_NOT_FOUND") throw e;
    return { Linter: null, missing: new Refusal(`ESLint cannot be loaded - ${LINT_HELP} (${String(e.message).split("\n")[0]})`) };
  }
}
const lint = await loadLinter();
let linter = null;

/* ------------------------------------------------------------------ read -- */
/* The engine is everything before the component banner; the one React
   import is blanked, not removed, so the line numbers hold. */
function engineBody(source) {
  const cut = source.indexOf(BANNER);
  if (cut < 0) refuse("the component banner is not in the reference");
  return source.slice(0, cut).replace(/^import .*from "react";$/m, "");
}
/* Every marker line: its section name and its line number, 1-based. */
function markersOf(body) {
  const out = [];
  body.split("\n").forEach((text, i) => { const m = MARKER.exec(text); if (m) out.push({ name: m[1], line: i + 1 }); });
  return out;
}
/* The markers must be SECTIONS, once each, in order; the first fault found. */
function markerFault(names) {
  const unknown = names.find((n) => !SECTIONS.includes(n));
  if (unknown) return `the marker "${unknown}" is not a section this extractor knows (${SECTIONS.join(", ")})`;
  const twice = names.find((n, i) => names.indexOf(n) !== i);
  if (twice) return `the marker "${twice}" appears twice`;
  const missing = SECTIONS.find((s) => !names.includes(s));
  if (missing) return `the marker "${missing}" is missing`;
  if (names.join() !== SECTIONS.join()) return `the markers are out of order: ${names.join(", ")}`;
  return null;
}

/* ESLint's parser and scope manager, in process: the top-level statements
   with their ranges, and every module-scope binding with the line it is
   declared on and the line of each reference to it. */
function parseBody(body) {
  if (lint.missing) throw lint.missing;
  linter ||= new lint.Linter({ configType: "flat" });
  let read = null;
  /** @type {import("eslint").Rule.RuleModule} */
  const collect = { create: (ctx) => ({ Program(node) {
    const scope = ctx.sourceCode.scopeManager.globalScope.childScopes[0];
    read = {
      statements: node.body.map((s) => ({ line: s.loc.start.line, last: s.loc.end.line })),
      bindings: scope.variables.map((v) => ({ name: v.name, line: v.defs[0].node.loc.start.line, defs: v.defs.map((d) => d.node.loc.start.line), uses: v.references.map((r) => ({ line: r.identifier.loc.start.line, write: r.isWrite() && !r.init })) })),
    };
  } }) };
  const messages = linter.verify(body, [{
    files: ["**/*.js"], plugins: { engine: { rules: { collect } } },
    languageOptions: { ecmaVersion: 2024, sourceType: "module" }, rules: { "engine/collect": "error" },
  }], { filename: "engine.js" });
  const fatal = messages.find((m) => m.fatal);
  if (fatal || !read) refuse(`the engine does not parse: line ${fatal ? fatal.line : "?"}: ${fatal ? fatal.message : "no program was read"}`);
  return read;
}

/* ----------------------------------------------------------------- place -- */
/* Which section a line is in: the last marker above it, or -1 above them all. */
const sectionAt = (markers, line) => markers.filter((m) => m.line < line).length - 1;
/* A statement above the first marker, or one spanning a marker line, is
   refused. */
function placeStatements(statements, markers) {
  for (const s of statements) {
    const at = sectionAt(markers, s.line);
    if (at < 0) refuse(`line ${s.line} is code before the first marker`);
    if (sectionAt(markers, s.last) !== at) refuse(`a marker sits inside the statement that starts at line ${s.line}`);
  }
}
/* The declarations of each section, and the names each section imports from
   the sections above it. A use of a name a LATER section declares is refused:
   the order of the sections is the order of the imports. An ASSIGNMENT to a
   name another section declares is refused too: in the one file it runs, and
   in the modules it throws, since an imported binding cannot be assigned. A
   declaration's own initialiser is not an assignment. A name declared in two
   sections - a `var` twice - is refused: the one file shares one binding, and
   two modules each declaring it would not load (the engineer's plant, accepted
   by the first version, 2026-09-13). */
function crossReferences(bindings, markers) {
  const declared = SECTIONS.map(() => []);
  const imports = SECTIONS.map(() => SECTIONS.map(() => new Set()));
  for (const b of bindings) {
    const home = sectionAt(markers, b.line);
    const again = b.defs.find((line) => sectionAt(markers, line) !== home);
    if (again !== undefined) refuse(`${b.name} is declared in ${SECTIONS[home]} (line ${b.line}) and again in ${SECTIONS[sectionAt(markers, again)]} (line ${again}) - the one file shares one binding, and the modules would not load`);
    declared[home].push(b.name);
    for (const use of b.uses) {
      const from = sectionAt(markers, use.line);
      if (from < home) refuse(`${SECTIONS[from]} uses ${b.name} (line ${use.line}), which ${SECTIONS[home]} declares below it (line ${b.line}) - a section may reach only the sections above it`);
      if (from !== home && use.write) refuse(`${SECTIONS[from]} assigns to ${b.name} (line ${use.line}), which ${SECTIONS[home]} declares (line ${b.line}) - the one-file reference would run it and the modules would throw, because an imported binding cannot be assigned`);
      if (from > home) imports[from][home].add(b.name);
    }
  }
  return { declared, imports };
}
/* The offsets each section's text spans: from the line after its marker to
   the next marker line, or to the end of the engine. */
function sectionOffsets(body, markers) {
  const starts = [0];
  for (let i = 0; i < body.length; i++) if (body[i] === "\n") starts.push(i + 1);
  return markers.map((m, i) => [starts[m.line], i + 1 < markers.length ? starts[markers[i + 1].line - 1] : body.length]);
}
function analyse(source) {
  const body = engineBody(source);
  const markers = markersOf(body);
  const fault = markerFault(markers.map((m) => m.name));
  if (fault) refuse(fault);
  const { statements, bindings } = parseBody(body);
  placeStatements(statements, markers);
  const { declared, imports } = crossReferences(bindings, markers);
  return { body, declared, imports, offsets: sectionOffsets(body, markers) };
}

/* ---------------------------------------------------------------- render -- */
/* One section's text, verbatim, then the clause exporting every top-level
   declaration it makes. */
function sectionText(plan, at) {
  const [from, to] = plan.offsets[at];
  const text = plan.body.slice(from, to);
  const names = plan.declared[at];
  return (text.endsWith("\n") ? text : text + "\n") + (names.length ? `export { ${names.join(", ")} };\n` : "");
}
const importLines = (needs) => needs.map((names, from) => (names.size ? `import { ${[...names].sort().join(", ")} } from "./${SECTIONS[from]}.js";\n` : "")).join("");
/* Every generated file as [path, text]: the modules in a folder of the
   index's name beside it, then the index. */
function render(plan, index) {
  const folder = basename(index, extname(index));
  const dir = join(dirname(index), folder);
  const files = SECTIONS.map((name, at) => [join(dir, name + ".js"), HEADER + importLines(plan.imports[at]) + sectionText(plan, at)]);
  files.push([index, HEADER + SECTIONS.map((s) => `export * from "./${folder}/${s}.js";`).join("\n") + "\n"]);
  return files;
}
const once = (source, index, renderer) => { const plan = analyse(source); return { files: renderer(plan, index), declared: plan.declared.flat() }; };
/* Two extractions of one input must agree byte for byte, or the extraction
   is refused: an output that moves between runs would fail the gauntlet's
   77-times rule at some later, worse moment. `renderer` is a parameter for
   the one control that plants a moving output. */
function extract(source, index, renderer = render) {
  const a = once(source, index, renderer), b = once(source, index, renderer);
  const moved = a.files.find(([path, text], i) => b.files[i][0] !== path || b.files[i][1] !== text);
  if (moved) refuse(`two extractions of the same reference differ at ${moved[0]}`);
  return a;
}
/* The modules' folder is the extractor's own: a module a renamed or removed
   section left behind is deleted before the engine is written, or ESLint would
   lint it, the src/engine coverage row would count it, and anything could import
   it though nothing makes it (the engineer's O3, 2026-09-13). Only .js files the
   extraction does not write, and only in that one folder. */
/* THE FOLDER IS TRUSTED BY WHAT IS IN IT, NOT BY ITS NAME. The modules' folder
   is named after the index, so `node tools/extract-engine.mjs reference tests.js`
   pointed the deletion at tests/ and would have emptied it with exit 0, and
   `app/src.js` would have overwritten app/src/storage.js (the engineer's E-S1,
   2026-09-13, every delete and write logged instead of done). Every module and
   index this extractor has ever written starts with HEADER, the same since before
   batch 2; a file that does not is someone else's, and nothing is touched. */
function notOurs(path) {
  if (!existsSync(path)) return false;
  return statSync(path).isDirectory() || !readFileSync(path, "utf8").startsWith(HEADER);
}
function guardTargets(index, dir) {
  /* a modules' folder that exists as a file is refused too, never a stack trace (G-M3) */
  if (existsSync(dir) && !statSync(dir).isDirectory()) refuse(`${dir} is a file where the engine's modules would go, so nothing is written; pass an index whose folder is the engine's own`);
  const inDir = existsSync(dir) ? readdirSync(dir).filter((e) => e.endsWith(".js")).map((e) => join(dir, e)) : [];
  const foreign = [index, ...inDir].find(notOurs);
  /* the advice covers both causes (G-M2): someone else's folder, or a module of the
     engine's own that lost its header to a killed write or a hand edit */
  if (foreign) refuse(`${foreign} is not a file this extractor wrote - it has no GENERATED header - so the engine is neither written over it nor beside it; if it is a module in the engine's own folder, delete it and extract again, otherwise pass an index whose folder is the engine's own`);
}
function writeFiles(files) {
  const modules = files.slice(0, -1).map(([path]) => resolve(path));
  guardTargets(resolve(files[files.length - 1][0]), dirname(modules[0]));
  const dir = dirname(modules[0]), keep = new Set(modules.map((path) => basename(path)));
  if (existsSync(dir)) for (const e of readdirSync(dir)) if (e.endsWith(".js") && !keep.has(e)) rmSync(join(dir, e));
  for (const [path, text] of files) { mkdirSync(dirname(resolve(path)), { recursive: true }); writeFileSync(resolve(path), text); }
}

/* ------------------------------------------------------- the import scan -- */
/* Every name a file under the roots imports from the engine - a static
   `import { a, b as c } from` or a destructured `const { a, b: c } = await
   import(` of "@engine" or of a path ending src/engine.js - with its file. */
const ENGINE_SPEC = /^(?:@engine|.*\/src\/engine\.js)$/;
/* The brace list is identifier-shaped - names, commas, `as`, whitespace and
   comments - so a generator that builds an import from template pieces
   (tools/gen-acceptance.mjs does) is never read as one. */
const LIST = String.raw`((?:[\w$\s,:]|\/\/[^\n]*|\/\*[\s\S]*?\*\/)*)`;
const STATIC = new RegExp(String.raw`import\s*\{` + LIST + String.raw`\}\s*from\s*["']([^"']+)["']`, "g");
const DYNAMIC = new RegExp(String.raw`const\s*\{` + LIST + String.raw`\}\s*=\s*await\s+import\(\s*["']([^"']+)["']\s*\)`, "g");
const namesIn = (list) => list.replace(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g, "").split(",").map((p) => p.trim().split(/\s+as\s+|:/)[0].trim()).filter(Boolean);
function usesIn(text, file) {
  const uses = [];
  for (const re of [STATIC, DYNAMIC]) {
    for (const m of text.matchAll(re)) if (ENGINE_SPEC.test(m[2])) for (const name of namesIn(m[1])) uses.push({ name, file });
  }
  return uses;
}
function walkFiles(dir, out = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) { if (e !== "node_modules" && e !== "dist") walkFiles(p, out); }
    else if (/\.(js|jsx|mjs)$/.test(e)) out.push(p);
  }
  return out;
}
function importedNames(roots) {
  const uses = [];
  for (const root of roots) {
    if (!existsSync(root)) refuse(`the import scan cannot find ${posix(root)} - it would check nothing there and say nothing`);
    for (const file of walkFiles(root)) uses.push(...usesIn(readFileSync(file, "utf8"), posix(file)));
  }
  return uses;
}
/* A name imported that no section declares is refused, naming the file. */
function checkImports(declared, uses) {
  const known = new Set(declared);
  const stranger = uses.find((u) => !known.has(u.name));
  if (stranger) refuse(`${stranger.file} imports ${stranger.name} from the engine, and no section declares it`);
  return uses.length;
}

/* -------------------------------------------------------------- controls -- */
const marker = (name) => `/* @engine ${name} */`;
/* The hook answers "eslint" the way a missing package does and leaves a mark
   that it did, so a control can tell a hook that hid ESLint from one that hid
   nothing. */
const hideEslintHook = (mark) => `import { writeFileSync } from "node:fs";\nexport async function resolve(spec, ctx, next) { if (spec === "eslint") { writeFileSync(${JSON.stringify(mark)}, "hidden"); throw Object.assign(new Error("Cannot find package eslint"), { code: "ERR_MODULE_NOT_FOUND" }); } return next(spec, ctx); }\n`;
/* The refusal's own message, or null when the input is accepted. A throw
   that is not a refusal is the extractor's own fault, and comes back named
   as a crash so the control that met it fails BY NAME rather than the whole
   self-test dying before its summary: with a refusal removed, the first
   draft's plants crashed the extractor a few lines later and four watched
   reds were a stack trace instead of a control line. */
const crashed = (e) => `crashed instead of refusing: ${String(e && e.message ? e.message : e)}`;
function refused(source, renderer = render) {
  try { extract(source, INDEX, renderer); return null; } catch (e) { return e instanceof Refusal ? e.message : crashed(e); }
}
const has = (message, needle) => (message || "").includes(needle);
function markerControls(T, source) {
  T("a marker missing from the reference is refused, naming it", has(refused(source.replace(marker("sounds") + "\n", "")), 'the marker "sounds" is missing'));
  T("a marker that appears twice is refused, naming it", has(refused(source.replace(marker("trays"), marker("trays") + "\n" + marker("trays"))), 'the marker "trays" appears twice'));
  T("a marker this extractor does not know is refused, naming it", has(refused(source.replace(marker("palette"), marker("colours"))), 'the marker "colours" is not a section'));
  const swapped = source.replace(/\/\* @engine (palette|chunker) \*\//g, (m, n) => marker(n === "palette" ? "chunker" : "palette"));
  T("markers out of the file's order are refused", has(refused(swapped), "the markers are out of order"));
  T("a declaration above the first marker is refused, naming its line", has(refused(source.replace(marker("content"), "const zzqEarly = 1;\n" + marker("content"))), "is code before the first marker"));
  const inside = source.replace(marker("palette") + "\n", "").replace("const C = {\n", "const C = {\n" + marker("palette") + "\n");
  T("a marker line inside a statement is refused, naming the statement's line", has(refused(inside), "a marker sits inside the statement"));
  T("an engine that does not parse is refused, naming the line", has(refused(source.replace(marker("palette"), "const = ;\n" + marker("palette"))), "the engine does not parse: line"));
}
function referenceControls(T, source) {
  const forward = refused(source.replace(marker("palette"), 'const zzqForward = chunkWord("cat");\n' + marker("palette")));
  T("a section using a name a later section declares is refused, naming both sections and the name",
    has(forward, "content uses chunkWord") && has(forward, "which chunker declares below it"));
  const written = refused(source.replace(marker("palette"), "let zzqCount = 0;\n" + marker("palette")).replace(marker("chunker"), "function zzqBump() { zzqCount += 1; return zzqCount; }\n" + marker("chunker")));
  T("a section assigning to a name another section declares is refused, naming both sections and the name - the one file would run it and the modules would throw",
    has(written, "palette assigns to zzqCount") && has(written, "which content declares"));
  const twice = refused(source.replace(marker("palette"), "var zzqV = 1;\n" + marker("palette")).replace(marker("chunker"), "var zzqV = 2;\n" + marker("chunker")));
  T("a name declared in two sections is refused, naming both - the one file shares it and the modules would not load",
    has(twice, "zzqV is declared in content") && has(twice, "again in palette"));
  T("an extraction whose output moves between two renders is refused, naming the file",
    has(refused(source, (plan, index) => render(plan, index).map(([p, t], i) => [p, i === 2 ? t + `// ${Math.random()}\n` : t])), "two extractions of the same reference differ at"));
  const uses = importedNames(IMPORT_ROOTS);
  const declared = analyse(source).declared.flat();
  T(`the real tree's imports of the engine are all declared - ${uses.length} names read across ${IMPORT_ROOTS.map(posix).join(", ")}, ${new Set(uses.map((u) => u.name)).size} distinct - and the scan read more than 100`,
    uses.length > 100 && refusedBy(() => checkImports(declared, uses)) === null);
  withScratch("extract-engine-", (box) => {
    const spec = "../src/engine.js";
    writeFileSync(join(box, "zzq.test.js"), `import { zzqNothing } from "${spec}";\nconst { LEVELS, buildTray: bt } = await import("${spec}");\n`);
    const planted = importedNames([box]);
    const message = refusedBy(() => checkImports(declared, planted));
    T("a file importing a name no section declares is refused, naming the file and the name, and the destructured dynamic import is read too",
      planted.length === 3 && has(message, "zzqNothing") && has(message, "zzq.test.js"));
  });
}
/* Without ESLint the extractor refuses with what to do. Planted as an
   importer that fails the way a clean clone's does; a loader that rethrew
   comes back here as a plain error and fails this control by name. */
async function lintControls(T) {
  const notFound = Object.assign(new Error("Cannot find package 'eslint' imported from tools/extract-engine.mjs"), { code: "ERR_MODULE_NOT_FOUND" });
  const help = await loadLinter(() => Promise.reject(notFound)).catch((e) => ({ Linter: null, missing: e }));
  T("without ESLint installed the extractor refuses with what to do - run npm ci at the repository root - and never a stack trace",
    help.missing instanceof Refusal && has(help.missing.message, "run npm ci at the repository root") && help.Linter === null);
  const broken = await loadLinter(() => Promise.reject(new Error("Unexpected token in the installed parser"))).then(() => "advised", (e) => (e instanceof Refusal ? "advised" : "thrown"));
  T("a broken ESLint install is thrown as it is - only a missing package gets the install advice", broken === "thrown");
  const lost = refusedBy(() => importedNames([join(ROOT, "no-such-folder-zzq")]));
  T("an import-scan root that does not exist is refused, naming it, rather than checking nothing", has(lost, "the import scan cannot find no-such-folder-zzq"));
}
function refusedBy(fn) { try { fn(); return null; } catch (e) { return e instanceof Refusal ? e.message : crashed(e); } }
/* The tree's own reference: the files it makes, imported from a scratch
   directory, and the engine's text coming back from them. */
async function treeControls(T, source) {
  const { files, declared } = extract(source, INDEX);
  /* Thirteen as a literal (E4): a count read from SECTIONS judged itself and stayed green
     with the sections cut to twelve, watched 2026-09-13. */
  T("the reference splits into the thirteen sections and their index, every file headed GENERATED",
    SECTIONS.length === 13 && files.length === 14 && files.every(([, t]) => t.startsWith(HEADER)));
  const index = files[files.length - 1][1];
  T("the index re-exports every section in order and nothing else",
    index === HEADER + SECTIONS.map((s) => `export * from "./engine/${s}.js";`).join("\n") + "\n");
  const specifiers = files.slice(0, -1).map(([, t]) => [...t.matchAll(/^import \{[^}]*\} from "\.\/([a-z]+)\.js";$/gm)].map((m) => m[1]));
  T("every module imports only from sections above it, one line per section",
    specifiers.every((list, at) => list.every((s) => SECTIONS.indexOf(s) < at) && new Set(list).size === list.length));
  const body = engineBody(source).split("\n");
  const expected = body.slice(body.findIndex((l) => MARKER.test(l))).filter((l) => !MARKER.test(l)).join("\n").replace(/\n$/, "");
  const back = files.slice(0, -1).map(([, t]) => t.slice(HEADER.length).replace(/^import \{[^\n]*\n/gm, "").replace(/^export \{[^\n]*\n$/m, "")).join("").replace(/\n$/, "");
  T("the modules carry the engine's own text line for line: strip the header, the import lines and the export clause and the body comes back byte for byte", back === expected);
  await withScratch("extract-engine-", async (box) => {
    const at = join(box, INDEX);
    writeFiles(files.map(([p, t]) => [join(box, p), t]));
    const folder = join(box, "src", "engine");
    writeFileSync(join(folder, "zzqold.js"), HEADER + "export const zzqOld = 1;\n");
    writeFileSync(join(folder, "notes.txt"), "not a module\n");
    writeFiles(files.map(([p, t]) => [join(box, p), t]));
    T("a module a renamed section left behind is deleted when the engine is written again; the thirteen stay, and a file that is not a module is left alone",
      !existsSync(join(folder, "zzqold.js")) && existsSync(join(folder, "notes.txt")) && SECTIONS.every((s) => existsSync(join(folder, s + ".js"))));
    rmSync(join(folder, "notes.txt"));
    /* a module that will not load fails this control by name, with the loader's own words */
    const engine = await import(pathToFileURL(at).href).catch((e) => ({ __failed: crashed(e) }));
    const names = Object.keys(engine).sort();
    T(`the generated index imports, and exports exactly the names the reference declares: ${declared.length}` + (engine.__failed ? ` - ${engine.__failed}` : ""),
      !engine.__failed && names.join() === [...declared].sort().join());
    T("the old surface is inside the new one: chunkWord, buildSession, migrate and C are exported", ["chunkWord", "buildSession", "migrate", "C"].every((n) => n in engine));
    const twice = [1, 2].map((n) => { const out = join(box, `run${n}`, "engine.js"); return { out, r: run(process.execPath, [fileURLToPath(import.meta.url), REFERENCE, out]) }; });
    T("two extractions by the command are byte-identical, file for file, and the command says what it wrote",
      twice.every(({ r }) => r.status === 0 && /Wrote .* \(13 modules, \d+ exports, \d+ engine imports checked\)/.test(r.out))
      && SECTIONS.every((s) => readFileSync(join(box, "run1", "engine", s + ".js"), "utf8") === readFileSync(join(box, "run2", "engine", s + ".js"), "utf8"))
      && readFileSync(twice[0].out, "utf8") === readFileSync(twice[1].out, "utf8"));
    /* The app's own way in: predev and prebuild run the command from app/
       with paths from there. The scan must still read the whole tree. */
    const fromApp = run(process.execPath, [fileURLToPath(import.meta.url), "../reference/word-quest.jsx", join(box, "app-run", "engine.js")], { cwd: join(ROOT, "app") });
    const checked = /(\d+) engine imports checked/.exec(fromApp.out);
    T("run from app/ the way the app's predev and prebuild run it, the import scan still reads app/src, tests and tools from the repository root - more than 100 engine imports checked",
      fromApp.status === 0 && checked !== null && Number(checked[1]) > 100);
    hiddenLintControls(T, box);
    foreignTargetControls(T, box);
  });
}
/* The command pointed at a folder it did not make, both ways: an index named
   after a folder of someone else's .js files (tests.js and tests/), and an index
   path that is already someone else's file. Refused, named, nothing touched. */
const refusedNaming = (r, needle) => r.status === 1 && has(r.out, needle);
const stillReads = (path, text) => existsSync(path) && readFileSync(path, "utf8") === text;
function foreignTargetControls(T, box) {
  const tests = join(box, "guard", "tests"), mine = join(tests, "a.test.js"), other = join(box, "guard", "other.js");
  mkdirSync(tests, { recursive: true });
  writeFileSync(mine, "// a test nobody generated\n");
  writeFileSync(other, "// a file nobody generated\n");
  const ref = join(ROOT, REFERENCE);
  const folderRun = run(process.execPath, [fileURLToPath(import.meta.url), ref, join(box, "guard", "tests.js")]);
  const fileRun = run(process.execPath, [fileURLToPath(import.meta.url), ref, other]);
  const untouched = stillReads(mine, "// a test nobody generated\n") && stillReads(other, "// a file nobody generated\n");
  T("an index whose folder holds .js files the extractor did not write, or whose own path is someone else's file, is refused naming the file, and nothing is deleted or written - tests.js would otherwise have emptied tests/",
    refusedNaming(folderRun, "a.test.js") && refusedNaming(fileRun, "other.js") && untouched && !existsSync(join(tests, "content.js")) && !existsSync(join(box, "guard", "other")));
  oddShapeControls(T, box, ref);
}
/* An index path that is a folder (G-M1), and a modules' folder that already
   exists as a file (G-M3): each refused by name, never a stack trace. */
function oddShapeControls(T, box, ref) {
  const asFolder = join(box, "guard", "folder.js"), asFile = join(box, "guard", "flat.js");
  mkdirSync(asFolder, { recursive: true });
  writeFileSync(join(box, "guard", "flat"), "not a folder\n");
  const folderIndex = run(process.execPath, [fileURLToPath(import.meta.url), ref, asFolder]);
  const fileFolder = run(process.execPath, [fileURLToPath(import.meta.url), ref, asFile]);
  const quiet = !/\n\s+at .+[(:]\d+/.test(folderIndex.out + fileFolder.out);
  T("an index path that is a folder, and a modules' folder that is a file, are refused by name, never a stack trace (G-M1, G-M3)",
    refusedNaming(folderIndex, "folder.js") && refusedNaming(fileFolder, "is a file where the engine's modules would go") && quiet && !existsSync(join(box, "guard", "folder")) && !existsSync(asFile));
}
/* The clean clone's condition without a clone: a resolve hook that answers
   "eslint" the way a missing package does, loaded before the real command and
   before a real importer of SECTIONS. The loader control above plants an
   importer; this runs the files themselves, so a static import of eslint put
   back at the top fails both lines (the engineer's A-S1: the loader control
   alone stayed green with exactly that fault back). */
function hiddenLintControls(T, box) {
  const hooks = join(box, "hide-eslint-hooks.mjs"), register = join(box, "hide-eslint.mjs"), importer = join(box, "import-sections.mjs"), mark = join(box, "eslint-hidden.mark");
  writeFileSync(hooks, hideEslintHook(mark));
  writeFileSync(register, `import { register } from "node:module";\nregister(${JSON.stringify(pathToFileURL(hooks).href)});\n`);
  writeFileSync(importer, `import { SECTIONS } from ${JSON.stringify(import.meta.url)};\nconsole.log("sections " + SECTIONS.length);\n`);
  const hide = ["--import", pathToFileURL(register).href];
  /* Each run must leave the hook's mark: a hook that hid nothing let the importer's
     control pass whenever the extractor loaded at all (the engineer's C-M1,
     reproduced with an inert hook). The mark is cleared before each run. */
  rmSync(mark, { force: true });
  const bare = run(process.execPath, [...hide, fileURLToPath(import.meta.url), "../reference/word-quest.jsx", join(box, "bare", "engine.js")], { cwd: join(ROOT, "app") });
  const bareHid = existsSync(mark);
  /* On a failure the line carries what the child printed: the hook's error code
     crosses Node's hooks thread, confirmed on Node 24 and not on the gauntlet
     workflow's Node 22, where a dropped code would turn this red for a reason worth
     reading. No stack trace means no frame with a location, so a message that
     merely starts a line with "at" is not taken for one. */
  const said = (r, hid) => ` - exit ${r.status}, ${hid ? "the hook hid ESLint" : "the hook never hid ESLint"}, the child said: ${r.out.replace(/\s+/g, " ").slice(0, 200)}`;
  const refusedWell = bareHid && bare.status === 1 && has(bare.out, "run npm ci at the repository root") && !/\n\s+at .+[(:]\d+/.test(bare.out);
  T("with ESLint hidden, the app's own prebuild command refuses with what to do - run npm ci at the repository root - exit 1 and no stack trace" + (refusedWell ? "" : said(bare, bareHid)), refusedWell);
  rmSync(mark, { force: true });
  const loads = run(process.execPath, [...hide, importer], { cwd: ROOT });
  const loaded = existsSync(mark) && loads.status === 0 && has(loads.out, "sections 13");
  T("with ESLint hidden, a tool importing SECTIONS from the extractor still loads" + (loaded ? "" : said(loads, existsSync(mark))), loaded);
}
async function selfTest() {
  const ok = [];
  const T = (name, pass) => ok.push([name, pass]);
  const source = readFileSync(join(ROOT, REFERENCE), "utf8");
  markerControls(T, source);
  referenceControls(T, source);
  await lintControls(T);
  await treeControls(T, source);
  return finish("extract-engine", ok);
}

/* --------------------------------------------------------------- command -- */
const RUN_AS_COMMAND = import.meta.url === pathToFileURL(process.argv[1] || "").href;
if (RUN_AS_COMMAND) {
  if (process.argv.includes("--self-test")) process.exit((await selfTest()) ? 1 : 0);
  const args = process.argv.slice(2).filter((a) => !a.startsWith("--"));
  const src = args[0] || REFERENCE, out = args[1] || INDEX;
  try {
    const { files, declared } = extract(readFileSync(args[0] ? resolve(src) : join(ROOT, REFERENCE), "utf8"), args[1] ? resolve(out) : join(ROOT, INDEX));
    const checked = checkImports(declared, importedNames(IMPORT_ROOTS));
    writeFiles(files);
    console.log(`Wrote ${out} (${SECTIONS.length} modules, ${declared.length} exports, ${checked} engine imports checked)`);
  } catch (e) {
    if (!(e instanceof Refusal)) throw e;
    console.error(`extract-engine refuses ${src}: ${e.message}`);
    process.exit(1);
  }
}
