/* THE EXTRACTOR: one reference file, the engine modules and their index
 * (batch 2 of the refactor, owner-ruled 2026-09-12, decision 1: "section
 * markers inside the one reference file, and the extractor emits modules
 * from them; no rule changes; the hand-typed export list goes away").
 *
 * WHAT IT MAKES. reference/word-quest.jsx stays one file that runs as a chat
 * artifact (E2). Everything before the component banner is the engine, and
 * inside it a `/* @engine <name> *\/` marker comment opens each section, in
 * the order SECTIONS below fixes. Each section becomes src/engine/<name>.js:
 * one `import` line for every section above it whose names it uses, the
 * section's text verbatim, and one `export { ... }` clause naming every
 * top-level declaration it makes; src/engine.js is the index that re-exports
 * every section, so nothing that imports the engine changes. The export
 * surface is DERIVED from the declarations: the list of 100 names this file
 * used to type by hand - 8 of them imported by nobody - is gone. The clause
 * sits at the end rather than an `export` keyword on each declaration so the
 * body stays byte-for-byte the reference's: an `export` token in front of
 * `const TRICKY` made the shape gate's duplication window at that seam match
 * the tools' exported string lists, one region more than the ceiling allows,
 * and E6 does not let a ceiling rise for a keyword.
 *
 * WHAT IT REFUSES, each with a control in --self-test:
 *   - a marker missing, doubled, unknown or out of order; code before the
 *     first marker; a marker line inside a statement; an engine that does
 *     not parse;
 *   - a forward reference: a section using a name a LATER section declares.
 *     The order of the sections is the order of the imports, so a cycle is
 *     impossible by construction - a forward reference is a cycle in waiting;
 *   - a name app/src, tests or tools import from the engine that no section
 *     declares (the scan reads static imports and destructured dynamic
 *     imports of "@engine" and of any ".../src/engine.js");
 *   - an output that differs between two extractions of the same input (the
 *     gauntlet's 77-times rule: every extraction is byte-identical).
 *
 * HOW IT READS THE CODE. ESLint's own parser and scope manager, in process,
 * the way tools/shape.mjs reads complexity: the module scope's bindings are
 * the declarations and their references are the uses, so a property key or
 * a word in a string never counts as a use and a shorthand property does.
 * No line of logic changes, and the self-test proves the engine's body
 * comes back from the modules line for line.
 *
 * Run:      node tools/extract-engine.mjs [reference] [index]
 *           (defaults reference/word-quest.jsx and src/engine.js; the modules
 *           land beside the index in a folder of the index's own name)
 * Controls: node tools/extract-engine.mjs --self-test
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync } from "node:fs";
import { dirname, resolve, join, basename, extname, relative, sep } from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";
import { Linter } from "eslint";
import { finish } from "./lib/selftest.mjs";
import { run, withScratch } from "./lib/proc.mjs";

export const SECTIONS = ["content", "palette", "chunker", "session", "storage", "sounds", "trays", "export"];
const MARKER = /^\/\* @engine ([a-z]+) \*\/$/;
const BANNER = "/* ============================================================ */\n\nexport default function WordQuest()";
const HEADER = "/* GENERATED by tools/extract-engine.mjs — do not edit by hand. */\n";
const REFERENCE = "reference/word-quest.jsx";
const INDEX = "src/engine.js";
const IMPORT_ROOTS = ["app/src", "tests", "tools"];

/* A refusal is the extractor's own verdict on its input; anything else that
   throws is a fault in the extractor, and the controls tell the two apart. */
class Refusal extends Error {}
const refuse = (why) => { throw new Refusal(why); };
const posix = (p) => relative(process.cwd(), resolve(p)).split(sep).join("/");

/* ------------------------------------------------------------------ read -- */
/* The engine is everything before the component banner; the one React
   import is blanked, not removed, so the line numbers hold. */
function engineBody(source) {
  const cut = source.indexOf(BANNER);
  if (cut < 0) refuse("the component banner is not in the reference");
  return source.slice(0, cut).replace(/^import .*from "react";$/m, "");
}
/* Every marker line: its section name and its line number, 1-based. */
function markersOf(body) {
  const out = [];
  body.split("\n").forEach((text, i) => { const m = MARKER.exec(text); if (m) out.push({ name: m[1], line: i + 1 }); });
  return out;
}
/* The markers must be SECTIONS, once each, in order; the first fault found. */
function markerFault(names) {
  const unknown = names.find((n) => !SECTIONS.includes(n));
  if (unknown) return `the marker "${unknown}" is not a section this extractor knows (${SECTIONS.join(", ")})`;
  const twice = names.find((n, i) => names.indexOf(n) !== i);
  if (twice) return `the marker "${twice}" appears twice`;
  const missing = SECTIONS.find((s) => !names.includes(s));
  if (missing) return `the marker "${missing}" is missing`;
  if (names.join() !== SECTIONS.join()) return `the markers are out of order: ${names.join(", ")}`;
  return null;
}

/* ESLint's parser and scope manager, in process: the top-level statements
   with their ranges, and every module-scope binding with the line it is
   declared on and the line of each reference to it. */
const linter = new Linter({ configType: "flat" });
function parseBody(body) {
  let read = null;
  /** @type {import("eslint").Rule.RuleModule} */
  const collect = { create: (ctx) => ({ Program(node) {
    const scope = ctx.sourceCode.scopeManager.globalScope.childScopes[0];
    read = {
      statements: node.body.map((s) => ({ line: s.loc.start.line, last: s.loc.end.line })),
      bindings: scope.variables.map((v) => ({ name: v.name, line: v.defs[0].node.loc.start.line, uses: v.references.map((r) => r.identifier.loc.start.line) })),
    };
  } }) };
  const messages = linter.verify(body, [{
    files: ["**/*.js"], plugins: { engine: { rules: { collect } } },
    languageOptions: { ecmaVersion: 2024, sourceType: "module" }, rules: { "engine/collect": "error" },
  }], { filename: "engine.js" });
  const fatal = messages.find((m) => m.fatal);
  if (fatal || !read) refuse(`the engine does not parse: line ${fatal ? fatal.line : "?"}: ${fatal ? fatal.message : "no program was read"}`);
  return read;
}

/* ----------------------------------------------------------------- place -- */
/* Which section a line is in: the last marker above it, or -1 above them all. */
const sectionAt = (markers, line) => markers.filter((m) => m.line < line).length - 1;
/* A statement above the first marker, or one spanning a marker line, is
   refused. */
function placeStatements(statements, markers) {
  for (const s of statements) {
    const at = sectionAt(markers, s.line);
    if (at < 0) refuse(`line ${s.line} is code before the first marker`);
    if (sectionAt(markers, s.last) !== at) refuse(`a marker sits inside the statement that starts at line ${s.line}`);
  }
}
/* The declarations of each section, and the names each section imports from
   the sections above it. A use of a name a LATER section declares is refused:
   the order of the sections is the order of the imports. */
function crossReferences(bindings, markers) {
  const declared = SECTIONS.map(() => []);
  const imports = SECTIONS.map(() => SECTIONS.map(() => new Set()));
  for (const b of bindings) {
    const home = sectionAt(markers, b.line);
    declared[home].push(b.name);
    for (const line of b.uses) {
      const from = sectionAt(markers, line);
      if (from < home) refuse(`${SECTIONS[from]} uses ${b.name} (line ${line}), which ${SECTIONS[home]} declares below it (line ${b.line}) - a section may reach only the sections above it`);
      if (from > home) imports[from][home].add(b.name);
    }
  }
  return { declared, imports };
}
/* The offsets each section's text spans: from the line after its marker to
   the next marker line, or to the end of the engine. */
function sectionOffsets(body, markers) {
  const starts = [0];
  for (let i = 0; i < body.length; i++) if (body[i] === "\n") starts.push(i + 1);
  return markers.map((m, i) => [starts[m.line], i + 1 < markers.length ? starts[markers[i + 1].line - 1] : body.length]);
}
function analyse(source) {
  const body = engineBody(source);
  const markers = markersOf(body);
  const fault = markerFault(markers.map((m) => m.name));
  if (fault) refuse(fault);
  const { statements, bindings } = parseBody(body);
  placeStatements(statements, markers);
  const { declared, imports } = crossReferences(bindings, markers);
  return { body, declared, imports, offsets: sectionOffsets(body, markers) };
}

/* ---------------------------------------------------------------- render -- */
/* One section's text, verbatim, then the clause exporting every top-level
   declaration it makes. */
function sectionText(plan, at) {
  const [from, to] = plan.offsets[at];
  const text = plan.body.slice(from, to);
  const names = plan.declared[at];
  return (text.endsWith("\n") ? text : text + "\n") + (names.length ? `export { ${names.join(", ")} };\n` : "");
}
const importLines = (needs) => needs.map((names, from) => (names.size ? `import { ${[...names].sort().join(", ")} } from "./${SECTIONS[from]}.js";\n` : "")).join("");
/* Every generated file as [path, text]: the modules in a folder of the
   index's name beside it, then the index. */
function render(plan, index) {
  const folder = basename(index, extname(index));
  const dir = join(dirname(index), folder);
  const files = SECTIONS.map((name, at) => [join(dir, name + ".js"), HEADER + importLines(plan.imports[at]) + sectionText(plan, at)]);
  files.push([index, HEADER + SECTIONS.map((s) => `export * from "./${folder}/${s}.js";`).join("\n") + "\n"]);
  return files;
}
const once = (source, index, renderer) => { const plan = analyse(source); return { files: renderer(plan, index), declared: plan.declared.flat() }; };
/* Two extractions of one input must agree byte for byte, or the extraction
   is refused: an output that moves between runs would fail the gauntlet's
   77-times rule at some later, worse moment. `renderer` is a parameter for
   the one control that plants a moving output. */
function extract(source, index, renderer = render) {
  const a = once(source, index, renderer), b = once(source, index, renderer);
  const moved = a.files.find(([path, text], i) => b.files[i][0] !== path || b.files[i][1] !== text);
  if (moved) refuse(`two extractions of the same reference differ at ${moved[0]}`);
  return a;
}
function writeFiles(files) {
  for (const [path, text] of files) { mkdirSync(dirname(resolve(path)), { recursive: true }); writeFileSync(resolve(path), text); }
}

/* ------------------------------------------------------- the import scan -- */
/* Every name a file under the roots imports from the engine - a static
   `import { a, b as c } from` or a destructured `const { a, b: c } = await
   import(` of "@engine" or of a path ending src/engine.js - with its file. */
const ENGINE_SPEC = /^(?:@engine|.*\/src\/engine\.js)$/;
/* The brace list is identifier-shaped - names, commas, `as`, whitespace and
   comments - so a generator that builds an import from template pieces
   (tools/gen-acceptance.mjs does) is never read as one. */
const LIST = String.raw`((?:[\w$\s,:]|\/\/[^\n]*|\/\*[\s\S]*?\*\/)*)`;
const STATIC = new RegExp(String.raw`import\s*\{` + LIST + String.raw`\}\s*from\s*["']([^"']+)["']`, "g");
const DYNAMIC = new RegExp(String.raw`const\s*\{` + LIST + String.raw`\}\s*=\s*await\s+import\(\s*["']([^"']+)["']\s*\)`, "g");
const namesIn = (list) => list.replace(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g, "").split(",").map((p) => p.trim().split(/\s+as\s+|:/)[0].trim()).filter(Boolean);
function usesIn(text, file) {
  const uses = [];
  for (const re of [STATIC, DYNAMIC]) {
    for (const m of text.matchAll(re)) if (ENGINE_SPEC.test(m[2])) for (const name of namesIn(m[1])) uses.push({ name, file });
  }
  return uses;
}
function walkFiles(dir, out = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) { if (e !== "node_modules" && e !== "dist") walkFiles(p, out); }
    else if (/\.(js|jsx|mjs)$/.test(e)) out.push(p);
  }
  return out;
}
function importedNames(roots) {
  const uses = [];
  for (const root of roots.filter(existsSync)) for (const file of walkFiles(root)) uses.push(...usesIn(readFileSync(file, "utf8"), posix(file)));
  return uses;
}
/* A name imported that no section declares is refused, naming the file. */
function checkImports(declared, uses) {
  const known = new Set(declared);
  const stranger = uses.find((u) => !known.has(u.name));
  if (stranger) refuse(`${stranger.file} imports ${stranger.name} from the engine, and no section declares it`);
  return uses.length;
}

/* -------------------------------------------------------------- controls -- */
const marker = (name) => `/* @engine ${name} */`;
/* The refusal's own message, or null when the input is accepted. A throw
   that is not a refusal is the extractor's own fault, and comes back named
   as a crash so the control that met it fails BY NAME rather than the whole
   self-test dying before its summary: with a refusal removed, the first
   draft's plants crashed the extractor a few lines later and four watched
   reds were a stack trace instead of a control line. */
const crashed = (e) => `crashed instead of refusing: ${String(e && e.message ? e.message : e)}`;
function refused(source, renderer = render) {
  try { extract(source, INDEX, renderer); return null; } catch (e) { return e instanceof Refusal ? e.message : crashed(e); }
}
const has = (message, needle) => (message || "").includes(needle);
function markerControls(T, source) {
  T("a marker missing from the reference is refused, naming it", has(refused(source.replace(marker("sounds") + "\n", "")), 'the marker "sounds" is missing'));
  T("a marker that appears twice is refused, naming it", has(refused(source.replace(marker("trays"), marker("trays") + "\n" + marker("trays"))), 'the marker "trays" appears twice'));
  T("a marker this extractor does not know is refused, naming it", has(refused(source.replace(marker("palette"), marker("colours"))), 'the marker "colours" is not a section'));
  const swapped = source.replace(/\/\* @engine (palette|chunker) \*\//g, (m, n) => marker(n === "palette" ? "chunker" : "palette"));
  T("markers out of the file's order are refused", has(refused(swapped), "the markers are out of order"));
  T("a declaration above the first marker is refused, naming its line", has(refused(source.replace(marker("content"), "const zzqEarly = 1;\n" + marker("content"))), "is code before the first marker"));
  const inside = source.replace(marker("palette") + "\n", "").replace("const C = {\n", "const C = {\n" + marker("palette") + "\n");
  T("a marker line inside a statement is refused, naming the statement's line", has(refused(inside), "a marker sits inside the statement"));
  T("an engine that does not parse is refused, naming the line", has(refused(source.replace(marker("palette"), "const = ;\n" + marker("palette"))), "the engine does not parse: line"));
}
function referenceControls(T, source) {
  const forward = refused(source.replace(marker("palette"), 'const zzqForward = chunkWord("cat");\n' + marker("palette")));
  T("a section using a name a later section declares is refused, naming both sections and the name",
    has(forward, "content uses chunkWord") && has(forward, "which chunker declares below it"));
  T("an extraction whose output moves between two renders is refused, naming the file",
    has(refused(source, (plan, index) => render(plan, index).map(([p, t], i) => [p, i === 2 ? t + `// ${Math.random()}\n` : t])), "two extractions of the same reference differ at"));
  const uses = importedNames(IMPORT_ROOTS);
  const declared = analyse(source).declared.flat();
  T(`the real tree's imports of the engine are all declared - ${uses.length} names read across ${IMPORT_ROOTS.join(", ")}, ${new Set(uses.map((u) => u.name)).size} distinct - and the scan read more than 100`,
    uses.length > 100 && refusedBy(() => checkImports(declared, uses)) === null);
  withScratch("extract-engine-", (box) => {
    const spec = "../src/engine.js";
    writeFileSync(join(box, "zzq.test.js"), `import { zzqNothing } from "${spec}";\nconst { LEVELS, buildTray: bt } = await import("${spec}");\n`);
    const planted = importedNames([box]);
    const message = refusedBy(() => checkImports(declared, planted));
    T("a file importing a name no section declares is refused, naming the file and the name, and the destructured dynamic import is read too",
      planted.length === 3 && has(message, "zzqNothing") && has(message, "zzq.test.js"));
  });
}
function refusedBy(fn) { try { fn(); return null; } catch (e) { return e instanceof Refusal ? e.message : crashed(e); } }
/* The tree's own reference: the files it makes, imported from a scratch
   directory, and the engine's text coming back from them. */
async function treeControls(T, source) {
  const { files, declared } = extract(source, INDEX);
  T("the reference splits into the eight sections and their index, every file headed GENERATED",
    files.length === SECTIONS.length + 1 && files.every(([, t]) => t.startsWith(HEADER)));
  const index = files[files.length - 1][1];
  T("the index re-exports every section in order and nothing else",
    index === HEADER + SECTIONS.map((s) => `export * from "./engine/${s}.js";`).join("\n") + "\n");
  const specifiers = files.slice(0, -1).map(([, t]) => [...t.matchAll(/^import \{[^}]*\} from "\.\/([a-z]+)\.js";$/gm)].map((m) => m[1]));
  T("every module imports only from sections above it, one line per section",
    specifiers.every((list, at) => list.every((s) => SECTIONS.indexOf(s) < at) && new Set(list).size === list.length));
  const body = engineBody(source).split("\n");
  const expected = body.slice(body.findIndex((l) => MARKER.test(l))).filter((l) => !MARKER.test(l)).join("\n").replace(/\n$/, "");
  const back = files.slice(0, -1).map(([, t]) => t.slice(HEADER.length).replace(/^import \{[^\n]*\n/gm, "").replace(/^export \{[^\n]*\n$/m, "")).join("").replace(/\n$/, "");
  T("the modules carry the engine's own text line for line: strip the header, the import lines and the export clause and the body comes back byte for byte", back === expected);
  await withScratch("extract-engine-", async (box) => {
    const at = join(box, INDEX);
    writeFiles(files.map(([p, t]) => [join(box, p), t]));
    /* a module that will not load fails this control by name, with the loader's own words */
    const engine = await import(pathToFileURL(at).href).catch((e) => ({ __failed: crashed(e) }));
    const names = Object.keys(engine).sort();
    T(`the generated index imports, and exports exactly the names the reference declares: ${declared.length}` + (engine.__failed ? ` - ${engine.__failed}` : ""),
      !engine.__failed && names.join() === [...declared].sort().join());
    T("the old surface is inside the new one: chunkWord, buildSession, migrate and C are exported", ["chunkWord", "buildSession", "migrate", "C"].every((n) => n in engine));
    const twice = [1, 2].map((n) => { const out = join(box, `run${n}`, "engine.js"); return { out, r: run(process.execPath, [fileURLToPath(import.meta.url), REFERENCE, out]) }; });
    T("two extractions by the command are byte-identical, file for file, and the command says what it wrote",
      twice.every(({ r }) => r.status === 0 && /Wrote .* \(8 modules, \d+ exports\)/.test(r.out))
      && SECTIONS.every((s) => readFileSync(join(box, "run1", "engine", s + ".js"), "utf8") === readFileSync(join(box, "run2", "engine", s + ".js"), "utf8"))
      && readFileSync(twice[0].out, "utf8") === readFileSync(twice[1].out, "utf8"));
  });
}
async function selfTest() {
  const ok = [];
  const T = (name, pass) => ok.push([name, pass]);
  const source = readFileSync(REFERENCE, "utf8");
  markerControls(T, source);
  referenceControls(T, source);
  await treeControls(T, source);
  return finish("extract-engine", ok);
}

/* --------------------------------------------------------------- command -- */
const RUN_AS_COMMAND = import.meta.url === pathToFileURL(process.argv[1] || "").href;
if (RUN_AS_COMMAND) {
  if (process.argv.includes("--self-test")) process.exit((await selfTest()) ? 1 : 0);
  const args = process.argv.slice(2).filter((a) => !a.startsWith("--"));
  const src = args[0] || REFERENCE, out = args[1] || INDEX;
  try {
    const { files, declared } = extract(readFileSync(resolve(src), "utf8"), out);
    checkImports(declared, importedNames(IMPORT_ROOTS));
    writeFiles(files);
    console.log(`Wrote ${out} (${SECTIONS.length} modules, ${declared.length} exports)`);
  } catch (e) {
    if (!(e instanceof Refusal)) throw e;
    console.error(`extract-engine refuses ${src}: ${e.message}`);
    process.exit(1);
  }
}
