/* Generates src/engine.js from the single-file reference build.
   The reference must stay one file to run as a chat artifact. The tests and the
   standalone app both consume the extracted module. */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

const SRC = process.argv[2] || "reference/word-quest.jsx";
const OUT = process.argv[3] || "src/engine.js";
const MARK = "/* ============================================================ */\n\nexport default function WordQuest()";

const src = readFileSync(resolve(SRC), "utf8");
const cut = src.indexOf(MARK);
if (cut < 0) { console.error("Component banner not found in " + SRC); process.exit(1); }

const body = src.slice(0, cut).replace(/^import .*from "react";$/m, "");
const EXPORTS = ["LEVELS","TRICKY","DIGRAPHS","HOMOPHONES","ADULT_JUDGED","adultNote","INTERVALS","SESSION_SIZE","PROMPT_CAP",
  "WORD_LEVEL","chunkWord","dashed","freshWordState","applyResult","shuffle","buildSession",
  "checkPromotion","heal","migrate","newState","buildMarkdown","loadState","saveState","feedbackParts",
  "ADVANCE_GUARD_MS","SPLASH_TIMEOUT_MS","STORE_KEY","C","LANGS","speak","hush","buzz","SR","feedbackSpeech","PRAISE",
  "SEAM_MS","VOICE_SENTENCES","voiceScript","clipPlan","resolvePack","TTS_UNSAFE_PRAISE","ttsSafePraise"];

mkdirSync(dirname(resolve(OUT)), { recursive: true });
writeFileSync(resolve(OUT),
  "/* GENERATED by tools/extract-engine.mjs — do not edit by hand. */\n" +
  body + "\nexport { " + EXPORTS.join(", ") + " };\n");
console.log("Wrote " + OUT + " (" + EXPORTS.length + " exports)");
