/* How common is each bank word, measured from the books this game already pins?
 *
 * Fault AQ: a mastered word returns only by a uniform lottery, and measured
 * against the hundred-level ladder that is a 551-session wait for every word
 * alike - the same maintenance budget spent on `ox` as on `the`. The owner
 * ruled frequency-banded maintenance on 2026-08-31, and ruled the source with
 * it: the fourteen public-domain books already pinned in tools/corpus/sources.json.
 *
 * WHY THOSE BOOKS AND NOT A FREQUENCY DATABASE. SUBTLEX-US covers more (~100
 * percent against 84.5) and its author permits any use, and Dolch 1936 is
 * public domain outright. Both were costed on the decision page and both need
 * a new file, a new licence note and a new provenance argument. These books
 * need none: they are already owner-approved, already byte-pinned, already
 * screened, and they are what a child actually reads in THIS game. It is also
 * what rung 1 of the dependency rule says to do - look in the repository first.
 *
 * THE GAP, STATED RATHER THAN HIDDEN. 174 bank words appear in none of the
 * books: `mom`, `sip`, `pad`, `pigpen` and their kind. They are phonics drill
 * words, invented for teaching and rare in real prose, and a child meets them
 * constantly anyway because they sit in the early levels. An unranked word
 * takes the MIDDLE band, never the rare one, so nothing can disappear through
 * a hole in the data. That is the owner's ruling and it is enforced below.
 *
 * WHAT IT WRITES. Two space-separated word lists spliced into the reference
 * build - common and rare. Everything else, ranked-but-middling or unranked
 * alike, is middle by omission, which is also what makes the default safe.
 * The engine may not read a JSON file (E2 keeps the reference build one file),
 * so the lists are literals, generated here and never typed by hand.
 *
 * Usage:
 *   node tools/word-bands.mjs            report the bands a person reads
 *   node tools/word-bands.mjs --write    splice the literals into the reference
 *   node tools/word-bands.mjs --check    fail if the reference disagrees
 *   node tools/word-bands.mjs --self-test  prove it catches (E5)
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const CORPUS = "tools/corpus/";
const REF = "reference/word-quest.jsx";

/* The band sizes are fractions of the WHOLE BANK, not of the ranked part, and
   that distinction was paid for. Sizing by rank instead put all 174 unranked
   words on top of a middle band already 30 percent of the ranked list, which
   swelled middle to 459 words and pushed its return interval to 656 sessions -
   WORSE than the 551 it was meant to improve, and not the 481 the owner was
   shown when he ruled. Sizing by the whole bank keeps the promise: the middle
   band is 30 percent of 1,123 whether or not the corpus could rank its
   members, and the unranked words take seats inside it rather than beside it.
   Separate from the SLOT split (50/35/15) in the engine, which says how often
   each band is drawn rather than how many words it holds. */
export const COMMON_SHARE = 0.20;
export const MIDDLE_SHARE = 0.30;

export function corpusCounts(dir = CORPUS) {
  const counts = new Map();
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".screened.txt"))) {
    for (const raw of readFileSync(dir + f, "utf8").toLowerCase().match(/[a-z']+/g) || []) {
      const w = raw.replace(/'/g, "");
      if (w) counts.set(w, (counts.get(w) || 0) + 1);
    }
  }
  return counts;
}

/* Bank words, split into the three bands. Unranked words are NOT returned in
   either list, which is exactly how they land in the middle. */
export function bands(bank, counts) {
  const ranked = bank.filter((w) => counts.has(w)).sort((a, b) => counts.get(b) - counts.get(a) || (a < b ? -1 : 1));
  const unranked = bank.filter((w) => !counts.has(w));
  const wantCommon = Math.round(bank.length * COMMON_SHARE);
  const wantMiddle = Math.round(bank.length * MIDDLE_SHARE);
  /* The unranked take their seats INSIDE middle, so middle's ranked share is
     whatever is left of its budget. It can reach zero if a corpus ranks almost
     nothing, and that is correct: the band is then all unranked words. */
  const middleRanked = Math.max(0, wantMiddle - unranked.length);
  return {
    common: ranked.slice(0, wantCommon),
    middle: ranked.slice(wantCommon, wantCommon + middleRanked),
    rare: ranked.slice(wantCommon + middleRanked),
    unranked,
  };
}

const MARK_A = "/* GENERATED by tools/word-bands.mjs - do not edit by hand */";
const MARK_B = "/* end generated bands */";

export function literals(b) {
  return `${MARK_A}
const BAND_COMMON = new Set("${b.common.join(" ")}".split(" "));
const BAND_RARE = new Set("${b.rare.join(" ")}".split(" "));
${MARK_B}`;
}

export function splice(refText, block) {
  const a = refText.indexOf(MARK_A);
  if (a < 0) return null;
  const b = refText.indexOf(MARK_B, a);
  if (b < 0) return null;
  return refText.slice(0, a) + block + refText.slice(b + MARK_B.length);
}

function bankWords() {
  /* read from the generated engine, which is the shipped truth */
  return import("../src/engine.js").then((E) => [...new Set(E.LEVELS.flatMap((L) => L.words))]);
}

function selfTest() {
  const fails = [];
  const T = (n, c) => { if (!c) fails.push(n); };
  const counts = new Map([["the", 100], ["cat", 50], ["ox", 3], ["gem", 1]]);
  const bank = ["the", "cat", "ox", "gem", "pigpen"];
  const b = bands(bank, counts);

  T("the commonest word lands in the common band", b.common.includes("the"));
  T("the rarest ranked word lands in the rare band", b.rare.includes("gem"));
  T("a word in no book is unranked, not rare - the owner's ruling",
    b.unranked.includes("pigpen") && !b.rare.includes("pigpen"));
  T("an unranked word is in NEITHER emitted list, so it defaults to middle",
    !literals(b).includes("pigpen"));
  T("every bank word lands in exactly one band",
    b.common.length + b.middle.length + b.rare.length + b.unranked.length === bank.length);
  T("ties break by spelling, so the same corpus always gives the same bands",
    JSON.stringify(bands(bank, counts)) === JSON.stringify(bands(bank, counts)));
  T("the splice is reversible - it finds both marks and replaces between them",
    splice(`x${MARK_A}OLD${MARK_B}y`, `${MARK_A}NEW${MARK_B}`) === `x${MARK_A}NEW${MARK_B}y`);
  T("a reference with no marks is refused rather than silently unchanged",
    splice("no marks here", "block") === null);
  T("control: a corpus that counts nothing ranks nothing, and every word goes middle",
    bands(bank, new Map()).unranked.length === bank.length
      && bands(bank, new Map()).common.length === 0);
  T("bands are sized off the WHOLE bank, so unranked words sit INSIDE middle, not beside it",
    (() => { const big = bands(["a","b","c","d","e","f","g","h","i","j"],
        new Map([["a",9],["b",8],["c",7],["d",6],["e",5]]));
      /* 10 words: common wants 2, middle wants 3 - and 5 are unranked, so middle
         is all unranked and no ranked word may join it. */
      return big.common.length === 2 && big.middle.length === 0 && big.unranked.length === 5
        && big.rare.length === 3; })());

  for (const f of fails) console.error("  FAIL " + f);
  console.log(fails.length === 0
    ? "word-bands self-test: 10 controls, all caught"
    : `word-bands self-test: ${fails.length} of 10 controls FAILED`);
  return fails.length ? 1 : 0;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const arg = process.argv[2];
  if (arg === "--self-test") process.exit(selfTest());

  const bank = await bankWords();
  const counts = corpusCounts();
  const b = bands(bank, counts);
  const block = literals(b);
  const ref = readFileSync(REF, "utf8");

  if (arg === "--write") {
    const out = splice(ref, block);
    if (!out) { console.error("word-bands: the generated markers are missing from " + REF); process.exit(1); }
    writeFileSync(REF, out);
    console.log(`word-bands: wrote ${b.common.length} common and ${b.rare.length} rare into ${REF}`);
    console.log("Now run: node tools/extract-engine.mjs");
  } else if (arg === "--check") {
    if (!ref.includes(block)) {
      console.error("  PROBLEM: the bands in " + REF + " disagree with the corpus - run node tools/word-bands.mjs --write");
      process.exit(1);
    }
    console.log(`word-bands: ${b.common.length} common, ${b.middle.length + b.unranked.length} middle, ${b.rare.length} rare, in step with the corpus`);
  } else {
    const total = [...counts.values()].reduce((a, c) => a + c, 0);
    console.log(`corpus: ${total.toLocaleString()} running words from ${readdirSync(CORPUS).filter((f) => f.endsWith(".screened.txt")).length} pinned books`);
    console.log(`bank:   ${bank.length} words\n`);
    console.log(`  common  ${String(b.common.length).padStart(4)}   ${b.common.slice(0, 12).join(" ")} ...`);
    console.log(`  middle  ${String(b.middle.length + b.unranked.length).padStart(4)}   (${b.middle.length} ranked + ${b.unranked.length} in no book)`);
    console.log(`  rare    ${String(b.rare.length).padStart(4)}   ... ${b.rare.slice(-12).join(" ")}`);
  }
}
